name: Build ZMK firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:3.0
    steps:
      - name: Checkout user config
        uses: actions/checkout@v3

      - name: Clone ZMK
        uses: actions/checkout@v3
        with:
          repository: zmkfirmware/zmk
          path: zmk
          ref: main
          submodules: true

      - name: Init West workspace
        run: |
          mkdir workspace
          cd workspace
          west init -l ../zmk/app
          west update

      - name: Build Photon
        run: |
          cd workspace
          west build -s ../zmk/app -d build/left -b photon -- -DSHIELD=photon

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: photon
          path: workspace/build/left/zephyr/zmk.uf2
