name: Build ZMK firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:3.0
    steps:
      - name: Checkout user config
        uses: actions/checkout@v3

      - name: Clone ZMK
        uses: actions/checkout@v3
        with:
          repository: zmkfirmware/zmk
          path: zmk
          ref: main
          submodules: true

      - name: Init west workspace
        run: |
          mkdir workspace
          cd workspace
          west init -l ../zmk/app
          west update

      - name: Build Photon (LEFT)
        run: |
          cd workspace
          west build -s ../zmk/app -d build/left -b photon -- -DSHIELD=photon

      - name: Build Photon (RIGHT)
        run: |
          cd workspace
          west build -s ../zmk/app -d build/right -b photon -- -DSHIELD=photon_right

      - name: Upload LEFT firmware
        uses: actions/upload-artifact@v4
        with:
          name: photon-left
          path: workspace/build/left/zephyr/zmk.uf2

      - name: Upload RIGHT firmware
        uses: actions/upload-artifact@v4
        with:
          name: photon-right
          path: workspace/build/right/zephyr/zmk.uf2
